left_file: "./assets/left.png"
right_file: "./assets/right.png"
intrinsic_file: "./assets/K.txt"
ckpt_dir: "./pretrained_models/model_best_bp2.pth"
out_dir: "./output/"
scale: 1.0
hiera: 0
z_far: 10.0
valid_iters: 32
get_pc: 1
remove_invisible: 1
denoise_cloud: 0
denoise_nb_points: 30
denoise_radius: 0.03
